fix: gateway deposit bug

diff --git a/dev/deploy-base b/dev/deploy-base
--- a/dev/deploy-base
+++ b/dev/deploy-base
@@ -6,37 +6,49 @@ source "$(dirname "$0")/utils"
 # Check if argument is provided
 if [ $# -ne 1 ]; then
     echo "Usage: $0 <chain-name>"
-    echo "chain-name: The chain to deploy to (e.g. base_sepolia, base_mainnet, xmtp_ropsten, xmtp_mainnet)"
+    echo "chain-name: The chain to deploy to (e.g. base_sepolia, base_mainnet, base_sepolia_gateway_tests, xmtp_ropsten, xmtp_mainnet, xmtp_ropsten_gateway_tests)"
     exit 1
 fi
 
 CHAIN_NAME=$1
 
 case "$CHAIN_NAME" in
-  base_sepolia)
-    DEPLOY_FUNC="deployBaseSettlementChainComponents()"
-    ENVIRONMENT="testnet-dev"
-    ;;
-  base_mainnet)
-    DEPLOY_FUNC="deployBaseSettlementChainComponents()"
-    ENVIRONMENT="mainnet"
-    ;;
-  xmtp_ropsten)
-    DEPLOY_FUNC="deployBaseAppChainComponents()"
-    ENVIRONMENT="testnet-dev"
-    ;;
-  xmtp_mainnet)
-    DEPLOY_FUNC="deployBaseAppChainComponents()"
-    ENVIRONMENT="mainnet"
-    ;;
-  *)
-    echo "Error: Invalid chain name. Must be one of: base_sepolia, base_mainnet, xmtp_ropsten, xmtp_mainnet"
-    exit 1
-    ;;
+    "base_sepolia")
+        DEPLOY_FUNC="deployBaseSettlementChainComponents()"
+        ENVIRONMENT="testnet-dev"
+        ;;
+    "base_mainnet")
+        DEPLOY_FUNC="deployBaseSettlementChainComponents()"
+        ENVIRONMENT="mainnet"
+        ;;
+    "base_sepolia_gateway_tests")
+        DEPLOY_FUNC="deployBaseSettlementChainComponents()"
+        ENVIRONMENT="testnet-gateways"
+        CHAIN_NAME="base_sepolia"
+        IS_GATEWAY_TESTING=true
+        ;;
+    "xmtp_ropsten")
+        DEPLOY_FUNC="deployBaseAppChainComponents()"
+        ENVIRONMENT="testnet-dev"
+        ;;
+    "xmtp_mainnet")
+        DEPLOY_FUNC="deployBaseAppChainComponents()"
+        ENVIRONMENT="mainnet"
+        ;;
+    "xmtp_ropsten_gateway_tests")
+        DEPLOY_FUNC="deployBaseAppChainComponents()"
+        ENVIRONMENT="testnet-gateways"
+        CHAIN_NAME="xmtp_ropsten"
+        IS_GATEWAY_TESTING=true
+        ;;
+    *)
+        echo "Error: Invalid chain name. Must be one of: base_sepolia, base_mainnet, base_sepolia_gateway_tests, xmtp_ropsten, xmtp_mainnet, xmtp_ropsten_gateway_tests"
+        exit 1
+        ;;
 esac
 
 echo "⧖ Deploying base contracts on $CHAIN_NAME."
 
-ENVIRONMENT=$ENVIRONMENT forge script script/Deploy.s.sol:DeployScripts --rpc-url "$CHAIN_NAME" --broadcast --slow --sig "$DEPLOY_FUNC"
+IS_GATEWAY_TESTING=$IS_GATEWAY_TESTING ENVIRONMENT=$ENVIRONMENT forge script script/Deploy.s.sol:DeployScripts --rpc-url "$CHAIN_NAME" --broadcast --slow --sig "$DEPLOY_FUNC"
 
 echo "✔ Done deploying base contracts on $CHAIN_NAME."
