Automate smart contract artifact generation by adding artifacts job to GitHub CI workflow (#67)
### Automate smart contract artifact generation by adding artifacts job
to GitHub CI workflow
* Added new `artifacts` job in
[.github/workflows/build-contracts-image.yml](https://github.com/xmtp/smart-contracts/pull/67/files#diff-99eaa6bf42545d7de37f60f8db70c2b9f80f29e928537b4a81e096bccbf47440)
that runs on Ubuntu, installs Foundry toolchain v1.0.0, and generates
contract artifacts using `dev/gen-artifacts` script
* Added `artifacts/` to
[.gitignore](https://github.com/xmtp/smart-contracts/pull/67/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947)
to exclude generated contract artifacts from version control
* Removed previously committed ABI and bytecode files for smart
contracts that will now be generated during CI

diff --git a/dev/gen-artifacts b/dev/gen-artifacts
--- a/dev/gen-artifacts
+++ b/dev/gen-artifacts
@@ -22,7 +22,9 @@ export build_info_file="${artifacts_dir}/build-info.json"
 
 mkdir -p "${build_dir}" "${artifacts_dir}" "${bytecode_dir}" "${abi_dir}"
 
-export forge_version=$(forge --version | grep "Version" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
+forge --version
+
+export forge_version=$(forge --version | grep "Version" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n1)
 
 function get_chain_id() {
     echo "⧖ Getting chain id from RPC ${1}"
@@ -343,7 +345,7 @@ function main() {
 }
 
 if [ "${forge_version}" != "1.0.0" ]; then
-    echo "ERROR: Forge version must be 1.0.0" >&2
+    echo "ERROR: Forge version must be 1.0.0. Got '${forge_version}'" >&2
     exit 1
 fi
 
