polish img

diff --git a/dev/gen-anvil-state b/dev/gen-anvil-state
--- a/dev/gen-anvil-state
+++ b/dev/gen-anvil-state
@@ -51,10 +51,7 @@ function deploy_contracts() {
 }
 
 function register_nodes() {
-    local local_anvil_url="http://localhost:8545"
     local node_registry_address=$(jq -r ".addresses.implementation" "${anvil_config_dir}/NodeRegistry.json")
-    local node_registry_add_node_abi="addNode(address,bytes,string,uint256)"
-    local node_registry_add_to_network_abi="addToNetwork(uint256)"
 
     # Node registry admin - first anvil private key
     local node_registry_admin_private_key="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
@@ -64,38 +61,61 @@ function register_nodes() {
     local node_1_signing_key="04ba5734d8f7091719471e7f7ed6b9df170dc70cc661ca05e688601ad984f068b0d67351e5f06073092499336ab0839ef8a521afd334e53807205fa2f08eec74f4"
     local node_1_url="http://localhost:5050"
     local node_1_id="100"
+    local node_1_minFee="0"
 
     # Node 2 - third anvil private key
     local node_2_address="0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
     local node_2_signing_key="049d9031e97dd78ff8c15aa86939de9b1e791066a0224e331bc962a2099a7b1f0464b8bbafe1535f2301c72c2cb3535b172da30b02686ab0393d348614f157fbdb"
     local node_2_url="http://localhost:5051"
     local node_2_id="200"
+    local node_2_minFee="0"
 
-    cast send "${node_registry_address}" "${node_registry_add_node_abi}" \
-        "${node_1_address}" \
-        "${node_1_signing_key}" \
-        "${node_1_url}" \
-        "0" \
-        --rpc-url "${local_anvil_url}" \
-        --private-key "${node_registry_admin_private_key}"
+    if ! do_registration "${node_1_address}" "${node_1_signing_key}" "${node_1_url}" "${node_1_id}" "${node_1_minFee}"; then
+        echo "ERROR: Failed to register and add node 1"
+        exit 1
+    fi
 
-    cast send "${node_registry_address}" "${node_registry_add_to_network_abi}" \
-        "${node_1_id}" \
-        --rpc-url "${local_anvil_url}" \
-        --private-key "${node_registry_admin_private_key}"
+    if ! do_registration "${node_2_address}" "${node_2_signing_key}" "${node_2_url}" "${node_2_id}" "${node_2_minFee}"; then
+        echo "ERROR: Failed to register and add node 2"
+        exit 1
+    fi
 
-    cast send "${node_registry_address}" "${node_registry_add_node_abi}" \
-        "${node_2_address}" \
-        "${node_2_signing_key}" \
-        "${node_2_url}" \
-        "0" \
-        --rpc-url "${local_anvil_url}" \
-        --private-key "${node_registry_admin_private_key}"
+    echo "Successfully registered and added nodes"
+}
 
-    cast send "${node_registry_address}" "${node_registry_add_to_network_abi}" \
-        "${node_2_id}" \
+function do_registration() {
+    local node_address=$1
+    local signing_key=$2
+    local url=$3
+    local node_id=$4
+    local stake_amount=$5
+
+    local local_anvil_url="http://localhost:8545"
+    local node_registry_add_node_abi="addNode(address,bytes,string,uint256)"
+    local node_registry_add_to_network_abi="addToNetwork(uint256)"
+
+    # Mint node operator NFT
+    if ! cast send "${node_registry_address}" "${node_registry_add_node_abi}" \
+        "${node_address}" \
+        "${signing_key}" \
+        "${url}" \
+        "${stake_amount}" \
         --rpc-url "${local_anvil_url}" \
-        --private-key "${node_registry_admin_private_key}"
+        --private-key "${node_registry_admin_private_key}"; then
+        echo "ERROR: Failed to mint node operator NFT, node ID: ${node_id}"
+        return 1
+    fi
+
+    # Add node to network
+    if ! cast send "${node_registry_address}" "${node_registry_add_to_network_abi}" \
+        "${node_id}" \
+        --rpc-url "${local_anvil_url}" \
+        --private-key "${node_registry_admin_private_key}"; then
+        echo "ERROR: Failed to add node to network, node ID: ${node_id}"
+        return 1
+    fi
+
+    return 0
 }
 
 function dump_state_info() {
@@ -123,6 +143,16 @@ function dump_state_info() {
 
 if ! command -v anvil &> /dev/null; then
     echo "ERROR: anvil could not be found"
+    exit 1
+fi
+
+if ! command -v cast &> /dev/null; then
+    echo "ERROR: cast could not be found"
+    exit 1
+fi
+
+if ! command -v jq &> /dev/null; then
+    echo "ERROR: jq could not be found"
     exit 1
 fi
 
